#!/bin/sh
echo 'ucx_ucc'
git pull origin emetrotel

cd plugins/mscs
echo ''
echo 'plugins/mscs'
git pull

cd ../ucx_presence
echo ''
echo 'plugins/ucx_presence'
git pull

cd ../ucx_adapter
echo ''
echo 'plugins/ucx_adapter'
git pull
