#!/bin/sh
echo 'ucx_ucc'
git status

cd plugins/mscs
echo ''
echo 'plugins/mscs'
git status

cd ../ucx_presence
echo ''
echo 'plugins/ucx_presence'
git status

cd ../ucx_adapter
echo ''
echo 'plugins/ucx_adapter'
git status
