defmodule UccSettings.Settings.Config.Message do
  use UccSettings.Settings, scope: inspect(__MODULE__), repo: UcxUcc.Repo, schema: [
    [name: "allow_message_editing", type: "boolean", default: "true"],
    [name: "block_message_editing_after", type: "integer", default: "0"],
    [name: "block_message_deleting_after", type: "integer", default: "0"],
    [name: "allow_message_deleting", type: "boolean", default: "true"],
    [name: "show_edited_status", type: "boolean", default: "true"],
    [name: "show_deleted_status", type: "boolean", default: "false"],
    [name: "allow_bad_words_filtering", type: "boolean", default: "false"],
    [name: "add_bad_words_to_blacklist", type: "string", default: ""],
    [name: "max_channel_size_for_all_message", type: "integer", default: "0"],
    [name: "max_channel_size_for_all_message", type: "integer", default: "0"],
    [name: "max_allowed_message_size", type: "integer", default: "5000"],
    [name: "show_formatting_tips", type: "boolean", default: "true"],
    [name: "grouping_period_seconds", type: "integer", default: "300"],
    [name: "embed_link_previews", type: "boolean", default: "true"],
    [name: "disable_embedded_for_users", type: "string", default: ""],
    [name: "embeded_ignore_hosts", type: "string", default: "localhost, 127.0.0.1, 10.0.0.0/8, 172.16.0.0/12, 192.168.0.0/16"],
    [name: "time_format", type: "string", default: "LT"],
    [name: "date_format", type: "string", default: "LL"],
    [name: "hide_user_join", type: "boolean", default: "false"],
    [name: "hide_user_leave", type: "boolean", default: "false"],
    [name: "hide_user_removed", type: "boolean", default: "false"],
    [name: "hide_user_added", type: "boolean", default: "false"],
    [name: "hide_user_muted", type: "boolean", default: "false"],
    [name: "allow_message_pinning", type: "boolean", default: "true"],
    [name: "allow_message_staring", type: "boolean", default: "true"],
    [name: "allow_message_snippeting", type: "boolean", default: "false"],
    [name: "autolinker_strip_prefix", type: "boolean", default: "false"],
    [name: "autolinker_scheme_urls", type: "boolean", default: "true"],
    [name: "autolinker_www_urls", type: "boolean", default: "true"],
    [name: "autolinker_tld_urls", type: "boolean", default: "true"],
    [name: "autolinker_url_regexl", type: "string", default: "(://|www\.).+"],
    [name: "autolinker_email", type: "boolean", default: "true"],
    [name: "autolinker_phone", type: "boolean", default: "true"]]

end
